### ISSUE TITLE
Text linking to social media accounts is clunky

### ISSUE THREAD

**Issue by scottcolfer** [scottcolfer/scottcolfer.github.io#40]
Currently, text on front page to highlight and link to social media accounts is clunky. Removing it and linking elsewhere would simplify this main text.

Minima has social link functionality according to its [readme](https://github.com/jekyll/minima). 
For my purposes it should look like the following 

```
# generate social links in footer
minima:
  social_links:
    twitter: [username]
    github: [username]
    linkedin: [username]
```

I'll try just Twitter first and see if it works.
